<a href="https://colab.research.google.com/github/Jauny143/Machine-Learning-Projects/blob/main/Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_14_naive_bayes/iphone_purchase_records.csv')

# **Load the** **Dataset**

In [3]:
df.head()

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [5]:
df.describe()

              Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

# Convert Gender to Number

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
label_encoder_gender = LabelEncoder()

In [8]:
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [10]:
df.head()

   Gender  Age  Salary  Purchase Iphone
0       1   19   19000                0
1       1   35   20000                0
2       0   26   43000                0
3       0   27   57000                0
4       1   19   76000                0

In [21]:
X = df.iloc[:,:-1].values
y = df.iloc[:, 3].values

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state=0)

In [24]:
from sklearn.preprocessing import StandardScaler
X_scaling = StandardScaler()
X_train = X_scaling.fit_transform(X_train)
X_test =  X_scaling.fit_transform(X_test)

In [25]:
X_train

array([[-0.98019606,  0.58164944, -0.88670699],
       [ 1.02020406, -0.60673761,  1.46173768],
       [-0.98019606, -0.01254409, -0.5677824 ],
       [-0.98019606, -0.60673761,  1.89663484],
       [-0.98019606,  1.37390747, -1.40858358],
       [-0.98019606,  1.47293972,  0.99784738],
       [ 1.02020406,  0.08648817, -0.79972756],
       [ 1.02020406, -0.01254409, -0.24885782],
       [-0.98019606, -0.21060859, -0.5677824 ],
       [-0.98019606, -0.21060859, -0.19087153],
       [-0.98019606, -0.30964085, -1.29261101],
       [ 1.02020406, -0.30964085, -0.5677824 ],
       [ 1.02020406,  0.38358493,  0.09905991],
       [-0.98019606,  0.8787462 , -0.59677555],
       [-0.98019606,  2.06713324, -1.17663843],
       [ 1.02020406,  1.07681071, -0.13288524],
       [-0.98019606,  0.68068169,  1.78066227],
       [-0.98019606, -0.70576986,  0.56295021],
       [-0.98019606,  0.77971394,  0.35999821],
       [-0.98019606,  0.8787462 , -0.53878926],
       [ 1.02020406, -1.20093113, -1.58254245],
       [ 1.02020406,  2.1661655 ,  0.93986109],
       [-0.98019606, -0.01254409,  1.22979253],
       [ 1.02020406,  0.18552042,  1.08482681],
       [-0.98019606,  0.38358493, -0.48080297],
       [ 1.02020406, -0.30964085, -0.30684411],
       [ 1.02020406,  0.97777845, -0.8287207 ],
       [-0.98019606,  0.97777845,  1.8676417 ],
       [-0.98019606, -0.01254409,  1.25878567],
       [ 1.02020406, -0.90383437,  2.27354572],
       [-0.98019606, -1.20093113, -1.58254245],
       [ 1.02020406,  2.1661655 , -0.79972756],
       [ 1.02020406, -1.39899564, -1.46656987],
       [ 1.02020406,  0.38358493,  2.30253886],
       [-0.98019606,  0.77971394,  0.76590222],
       [ 1.02020406, -1.00286662, -0.30684411],
       [ 1.02020406,  0.08648817,  0.76590222],
       [ 1.02020406, -1.00286662,  0.56295021],
       [ 1.02020406,  0.28455268,  0.07006676],
       [ 1.02020406,  0.68068169, -1.26361786],
       [-0.98019606, -0.50770535, -0.01691267],
       [-0.98019606, -1.79512465,  0.35999821],
       [ 1.02020406, -0.70576986,  0.12805305],
       [ 1.02020406,  0.38358493,  0.30201192],
       [-0.98019606, -0.30964085,  0.07006676],
       [-0.98019606, -0.50770535,  2.30253886],
       [ 1.02020406,  0.18552042,  0.04107362],
       [-0.98019606,  1.27487521,  2.21555943],
       [ 1.02020406,  0.77971394,  0.27301877],
       [ 1.02020406, -0.30964085,  0.1570462 ],
       [ 1.02020406, -0.01254409, -0.53878926],
       [-0.98019606, -0.21060859,  0.1570462 ],
       [-0.98019606, -0.11157634,  0.24402563],
       [ 1.02020406, -0.01254409, -0.24885782],
       [-0.98019606,  2.1661655 ,  1.11381995],
       [-0.98019606, -1.79512465,  0.35999821],
       [ 1.02020406,  1.86906873,  0.12805305],
       [ 1.02020406,  0.38358493, -0.13288524],
       [ 1.02020406, -1.20093113,  0.30201192],
       [ 1.02020406,  0.77971394,  1.37475825],
       [ 1.02020406, -0.30964085, -0.24885782],
       [-0.98019606, -1.6960924 , -0.04590581],
       [-0.98019606, -1.00286662, -0.74174127],
       [ 1.02020406,  0.28455268,  0.50496393],
       [-0.98019606, -0.11157634, -1.06066585],
       [ 1.02020406, -1.10189888,  0.59194336],
       [ 1.02020406,  0.08648817, -0.79972756],
       [ 1.02020406, -1.00286662,  1.54871711],
       [-0.98019606, -0.70576986,  1.40375139],
       [ 1.02020406, -1.29996338,  0.50496393],
       [-0.98019606, -0.30964085,  0.04107362],
       [ 1.02020406, -0.11157634,  0.01208048],
       [ 1.02020406, -0.30964085, -0.88670699],
       [ 1.02020406,  0.8787462 , -1.3505973 ],
       [-0.98019606, -0.30964085,  2.24455257],
       [-0.98019606,  0.97777845,  1.98361427],
       [ 1.02020406, -1.20093113,  0.47597078],
       [ 1.02020406, -1.29996338,  0.27301877],
       [-0.98019606,  1.37390747,  1.98361427],
       [ 1.02020406,  1.27487521, -1.3505973 ],
       [-0.98019606, -0.30964085, -0.27785096],
       [-0.98019606, -0.50770535,  1.25878567],
       [ 1.02020406, -0.80480212,  1.08482681],
       [ 1.02020406,  0.97777845, -1.06066585],
       [-0.98019606,  0.28455268,  0.30201192],
       [-0.98019606,  0.97777845,  0.76590222],
       [ 1.02020406, -0.70576986, -1.49556302],
       [-0.98019606, -0.70576986,  0.04107362],
       [ 1.02020406,  0.48261718,  1.72267598],
       [-0.98019606,  2.06713324,  0.18603934],
       [-0.98019606, -1.99318916, -0.74174127],
       [ 1.02020406, -0.21060859,  1.40375139],
       [-0.98019606,  0.38358493,  0.59194336],
       [-0.98019606,  0.8787462 , -1.14764529],
       [-0.98019606, -1.20093113, -0.77073441],
       [ 1.02020406,  0.18552042,  0.24402563],
       [ 1.02020406,  0.77971394, -0.30684411],
       [-0.98019606,  2.06713324, -0.79972756],
       [-0.98019606,  0.77971394,  0.12805305],
       [ 1.02020406, -0.30964085,  0.6209365 ],
       [-0.98019606, -1.00286662, -0.30684411],
       [ 1.02020406,  0.18552042, -0.3648304 ],
       [ 1.02020406,  2.06713324,  2.12857999],
       [-0.98019606,  1.86906873, -1.26361786],
       [-0.98019606,  1.37390747, -0.91570013],
       [-0.98019606,  0.8787462 ,  1.25878567],
       [-0.98019606,  1.47293972,  2.12857999],
       [ 1.02020406, -0.30964085, -1.23462472],
       [-0.98019606,  1.96810099,  0.91086794],
       [-0.98019606,  0.68068169, -0.71274813],
       [-0.98019606, -1.49802789,  0.35999821],
       [ 1.02020406,  0.77971394, -1.3505973 ],
       [ 1.02020406,  0.38358493, -0.13288524],
       [-0.98019606, -1.00286662,  0.41798449],
       [ 1.02020406, -0.01254409, -0.30684411],
       [-0.98019606, -1.20093113,  0.41798449],
       [-0.98019606, -0.90383437, -1.20563157],
       [-0.98019606, -0.11157634,  0.04107362],
       [-0.98019606, -1.59706014, -0.42281668],
       [-0.98019606,  0.97777845, -1.00267957],
       [ 1.02020406,  1.07681071, -1.20563157],
       [-0.98019606, -0.01254409, -0.13288524],
       [-0.98019606, -1.10189888, -1.52455616],
       [ 1.02020406,  0.77971394, -1.20563157],
       [ 1.02020406,  0.97777845,  2.07059371],
       [-0.98019606, -1.20093113, -1.52455616],
       [-0.98019606, -0.30964085,  0.79489537],
       [-0.98019606,  0.08648817, -0.30684411],
       [-0.98019606, -1.39899564, -1.23462472],
       [ 1.02020406, -0.60673761, -1.49556302],
       [ 1.02020406,  0.77971394,  0.53395707],
       [ 1.02020406, -0.30964085, -0.33583725],
       [ 1.02020406,  1.77003648, -0.27785096],
       [ 1.02020406,  0.8787462 , -1.03167271],
       [-0.98019606,  0.18552042,  0.07006676],
       [ 1.02020406, -0.60673761,  0.8818748 ],
       [-0.98019606, -1.89415691, -1.40858358],
       [ 1.02020406, -1.29996338,  0.59194336],
       [ 1.02020406, -0.30964085,  0.53395707],
       [ 1.02020406, -1.00286662, -1.089659  ],
       [-0.98019606,  1.17584296, -1.43757673],
       [ 1.02020406,  0.18552042, -0.30684411],
       [-0.98019606,  1.17584296, -0.74174127],
       [ 1.02020406, -0.30964085,  0.07006676],
       [-0.98019606,  0.18552042,  2.09958685],
       [-0.98019606,  0.77971394, -1.089659  ],
       [-0.98019606,  0.08648817,  0.04107362],
       [ 1.02020406, -1.79512465,  0.12805305],
       [ 1.02020406, -0.90383437,  0.1570462 ],
       [ 1.02020406, -0.70576986,  0.18603934],
       [ 1.02020406,  0.8787462 , -1.29261101],
       [ 1.02020406,  0.18552042, -0.24885782],
       [ 1.02020406, -0.4086731 ,  1.22979253],
       [-0.98019606, -0.01254409,  0.30201192],
       [-0.98019606,  0.38358493,  0.1570462 ],
       [-0.98019606,  0.8787462 , -0.65476184],
       [-0.98019606,  0.08648817,  0.1570462 ],
       [ 1.02020406, -1.89415691, -1.29261101],
       [-0.98019606, -0.11157634,  0.30201192],
       [ 1.02020406, -0.21060859, -0.27785096],
       [ 1.02020406,  0.28455268, -0.50979612],
       [ 1.02020406, -0.21060859,  1.6067034 ],
       [-0.98019606,  0.97777845, -1.17663843],
       [-0.98019606, -0.21060859,  1.63569655],
       [-0.98019606,  1.27487521,  1.8676417 ],
       [-0.98019606, -1.10189888, -0.3648304 ],
       [ 1.02020406, -0.01254409,  0.04107362],
       [-0.98019606,  0.08648817, -0.24885782],
       [-0.98019606, -1.59706014, -1.23462472],
       [-0.98019606, -0.50770535, -0.27785096],
       [ 1.02020406,  0.97777845,  0.12805305],
       [-0.98019606,  1.96810099, -1.3505973 ],
       [ 1.02020406,  1.47293972,  0.07006676],
       [-0.98019606, -0.60673761,  1.37475825],
       [ 1.02020406,  1.57197197,  0.01208048],
       [ 1.02020406, -0.80480212,  0.30201192],
       [-0.98019606,  1.96810099,  0.73690908],
       [-0.98019606, -1.20093113, -0.50979612],
       [ 1.02020406,  0.68068169,  0.27301877],
       [ 1.02020406, -1.39899564, -0.42281668],
       [ 1.02020406,  0.18552042,  0.1570462 ],
       [-0.98019606, -0.50770535, -1.20563157],
       [-0.98019606,  0.58164944,  2.01260742],
       [ 1.02020406, -1.59706014, -1.49556302],
       [-0.98019606, -0.50770535, -0.53878926],
       [-0.98019606,  0.48261718,  1.83864855],
       [-0.98019606, -1.39899564, -1.089659  ],
       [-0.98019606,  0.77971394, -1.37959044],
       [ 1.02020406, -0.30964085, -0.42281668],
       [-0.98019606,  1.57197197,  0.99784738],
       [-0.98019606,  0.97777845,  1.43274454],
       [ 1.02020406, -0.30964085, -0.48080297],
       [ 1.02020406, -0.11157634,  2.15757314],
       [-0.98019606, -1.49802789, -0.1038921 ],
       [-0.98019606, -0.11157634,  1.95462113],
       [ 1.02020406, -0.70576986, -0.33583725],
       [-0.98019606, -0.50770535, -0.8287207 ],
       [-0.98019606,  0.68068169, -1.37959044],
       [ 1.02020406, -0.80480212, -1.58254245],
       [ 1.02020406, -1.89415691, -1.46656987],
       [ 1.02020406,  1.07681071,  0.12805305],
       [ 1.02020406,  0.08648817,  1.51972397],
       [ 1.02020406, -0.30964085,  0.09905991],
       [ 1.02020406,  0.08648817,  0.04107362],
       [ 1.02020406, -1.39899564, -1.3505973 ],
       [-0.98019606,  0.28455268,  0.07006676],
       [-0.98019606, -0.90383437,  0.38899135],
       [-0.98019606,  1.57197197, -1.26361786],
       [-0.98019606, -0.30964085, -0.74174127],
       [ 1.02020406, -0.11157634,  0.1570462 ],
       [-0.98019606, -0.90383437, -0.65476184],
       [-0.98019606, -0.70576986, -0.04590581],
       [ 1.02020406,  0.38358493, -0.45180983],
       [ 1.02020406, -0.80480212,  1.89663484],
       [-0.98019606,  1.37390747,  1.28777882],
       [-0.98019606,  1.17584296, -0.97368642],
       [ 1.02020406,  1.77003648,  1.83864855],
       [ 1.02020406, -0.90383437, -0.24885782],
       [ 1.02020406, -0.80480212,  0.56295021],
       [ 1.02020406, -1.20093113, -1.5535493 ],
       [ 1.02020406, -0.50770535, -1.11865214],
       [-0.98019606,  0.28455268,  0.07006676],
       [ 1.02020406, -0.21060859, -1.06066585],
       [-0.98019606,  1.67100423,  1.6067034 ],
       [-0.98019606,  0.97777845,  1.78066227],
       [-0.98019606,  0.28455268,  0.04107362],
       [-0.98019606, -0.80480212, -0.21986468],
       [ 1.02020406, -0.11157634,  0.07006676],
       [-0.98019606,  0.28455268, -0.19087153],
       [-0.98019606,  1.96810099, -0.65476184],
       [-0.98019606, -0.80480212,  1.3457651 ],
       [ 1.02020406, -1.79512465, -0.59677555],
       [ 1.02020406, -0.11157634,  0.12805305],
       [ 1.02020406,  0.28455268, -0.30684411],
       [ 1.02020406,  1.07681071,  0.56295021],
       [ 1.02020406, -1.00286662,  0.27301877],
       [-0.98019606,  1.47293972,  0.35999821],
       [ 1.02020406,  0.18552042, -0.3648304 ],
       [ 1.02020406,  2.1661655 , -1.03167271],
       [ 1.02020406, -0.30964085,  1.11381995],
       [ 1.02020406, -1.6960924 ,  0.07006676],
       [ 1.02020406, -0.01254409,  0.04107362],
       [ 1.02020406,  0.08648817,  1.05583366],
       [-0.98019606, -0.11157634, -0.3648304 ],
       [-0.98019606, -1.20093113,  0.07006676],
       [-0.98019606, -0.30964085, -1.3505973 ],
       [-0.98019606,  1.57197197,  1.11381995],
       [ 1.02020406, -0.80480212, -1.52455616],
       [ 1.02020406,  0.08648817,  1.8676417 ],
       [ 1.02020406, -0.90383437, -0.77073441],
       [ 1.02020406, -0.50770535, -0.77073441],
       [ 1.02020406, -0.30964085, -0.91570013],
       [ 1.02020406,  0.28455268, -0.71274813],
       [-0.98019606,  0.28455268,  0.07006676],
       [-0.98019606,  0.08648817,  1.8676417 ],
       [-0.98019606, -1.10189888,  1.95462113],
       [-0.98019606, -1.6960924 , -1.5535493 ],
       [ 1.02020406, -1.20093113, -1.089659  ],
       [ 1.02020406, -0.70576986, -0.1038921 ],
       [-0.98019606,  0.08648817,  0.09905991],
       [ 1.02020406,  0.28455268,  0.27301877],
       [-0.98019606,  0.8787462 , -0.5677824 ],
       [-0.98019606,  0.28455268, -1.14764529],
       [-0.98019606, -0.11157634,  0.67892279],
       [-0.98019606,  2.1661655 , -0.68375498],
       [ 1.02020406, -1.29996338, -1.37959044],
       [-0.98019606, -1.00286662, -0.94469328],
       [-0.98019606, -0.01254409, -0.42281668],
       [-0.98019606, -0.21060859, -0.45180983],
       [-0.98019606, -1.79512465, -0.97368642],
       [-0.98019606,  1.77003648,  0.99784738],
       [ 1.02020406,  0.18552042, -0.3648304 ],
       [-0.98019606,  0.38358493,  1.11381995],
       [-0.98019606, -1.79512465, -1.3505973 ],
       [ 1.02020406,  0.18552042, -0.13288524],
       [ 1.02020406,  0.8787462 , -1.43757673],
       [-0.98019606, -1.99318916,  0.47597078],
       [ 1.02020406, -0.30964085,  0.27301877],
       [-0.98019606,  1.86906873, -1.06066585],
       [-0.98019606, -0.4086731 ,  0.07006676],
       [-0.98019606,  1.07681071, -0.88670699],
       [-0.98019606, -1.10189888, -1.11865214],
       [ 1.02020406, -1.89415691,  0.01208048],
       [-0.98019606,  0.08648817,  0.27301877],
       [ 1.02020406, -1.20093113,  0.33100506],
       [ 1.02020406, -1.29996338,  0.30201192],
       [-0.98019606, -1.00286662,  0.44697764],
       [ 1.02020406,  1.67100423, -0.88670699],
       [-0.98019606,  1.17584296,  0.53395707],
       [ 1.02020406,  1.07681071,  0.53395707],
       [ 1.02020406,  1.37390747,  2.331532  ],
       [-0.98019606, -0.30964085, -0.13288524],
       [ 1.02020406,  0.38358493, -0.45180983],
       [ 1.02020406, -0.4086731 , -0.77073441],
       [ 1.02020406, -0.11157634, -0.50979612],
       [-0.98019606,  0.97777845, -1.14764529],
       [ 1.02020406, -0.90383437, -0.77073441],
       [ 1.02020406, -0.21060859, -0.50979612],
       [-0.98019606, -1.10189888, -0.45180983],
       [-0.98019606, -1.20093113,  1.40375139]])

In [27]:
from sklearn.naive_bayes import GaussianNB
Classifier = GaussianNB()
Classifier.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [28]:
y_pred = Classifier.predict(X_test)

In [30]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

[[64  4]
 [ 5 27]]
Accuracy score: 0.91
Precision score: 0.8709677419354839
Recall score: 0.84375